### ISSUE TITLE
installation error for development_simple branch

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscale_core#138]
I tried to install jumpscale on development_simple branch but got this error:
```
    Installed /opt/code/github/threefoldtech/jumpscale_core
    Running post install task
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/code/github/threefoldtech/jumpscale_core/setup.py", line 135, in <module>
        'cmds/js_doc',
      File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/opt/python/3.5.2/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/python/3.5.2/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/python/3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/code/github/threefoldtech/jumpscale_core/setup.py", line 52, in run
        msg="Running post install task")
      File "/opt/python/3.5.2/lib/python3.5/distutils/cmd.py", line 336, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/opt/python/3.5.2/lib/python3.5/distutils/util.py", line 301, in execute
        func(*args)
      File "/opt/code/github/threefoldtech/jumpscale_core/setup.py", line 21, in _post_install
        from Jumpscale import j
      File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/__init__.py", line 177, in <module>
        j.core.jsgenerator.generate(methods_find=True)
      File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/core/generator/JSGenerator.py", line 53, in generate
        jsmodpath = os.path.join(os.fspath(dpath2), ".jumpscalemodules")
    AttributeError: module 'os' has no attribute 'fspath'
```

**Comment by rkhamis** [comment]
Whoever looks into this should be aware that jumpscale 9.5.1 uses python3.6. Just the configuration of travis needs to be adapted

**Comment by zaibon** [comment]
haa ok so that's the reason, thanks, I'll retry with a proper python version
