### ISSUE TITLE
Key cannot be used for signing

### ISSUE THREAD

**Issue by FastGeert** [threefoldtech/jumpscale_core#141]
#### Installation information

- jumpscale version: core commit: 81301a84ddf956f36cfdedc0466fcac091ca6271
- operating system: Ubuntu 16/04

#### Detailed description
After deploying 91 minio's, suddenly this error started appearing. Restarting 0-robot did not help.

#### Relevant stacktraces
```
[Sun21 09:59] - dm_vm.py          :56  :service-3003184f-9737-45aa-9332-dd5af01cd040 - INFO     - Monitor vm ca3206c9-a848-4b65-9ac6-55e26875cddc
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 137, in update_state
    vm_robot, _ = self._vm_robot_and_ip()
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 304, in _vm_robot_and_ip
    vminfo = vm.schedule_action('info', args={'timeout': 1200}).wait(die=True).result
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 131, in wait
    raise RuntimeError(self.eco.message)
RuntimeError: key cannot be used for signing
```

**Comment by zaibon** [comment]
@rkhamis

**Comment by rkhamis** [comment]
Seems that we set the ttl of the keys loaded to 24 hours by default. Which means any robot running for over that will suddenly find itself accessing a key that no longer exists in the ssh-agent
