### ISSUE TITLE
zrobot fails to restart on a bancadati node

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscale_core#152]
On one of the bancadati nodes with id `ac1f6b479e68` and ip `172.30.202.220`, I killed the zrobot process, and now it fails to restart because of the following error

``` 2018-11-26T13:08:49.498Z: logger D >  [1]zrobot 2|[Mon26 13:08] - .startup.py       :47  :j.zrobot_statup      - INFO     - farmer_id expired, trying to refresh
2018-11-26T13:08:49.621Z: logger D >  [1]zrobot 2|[Mon26 13:08] - DbConfigManager.py:104 :anager.dbconfigmanager - INFO     - using namespace ac1f6b479e68
2018-11-26T13:08:49.751Z: logger D >  [1]zrobot 2|[Mon26 13:08] - .startup.py       :66  :j.zrobot_statup      - INFO     - admin organization found: bancadati.threefold.grid.farm01
2018-11-26T13:08:49.751Z: logger D >  [1]zrobot 2|[Mon26 13:08] - .startup.py       :110 :j.zrobot_statup      - INFO     - detect if zdb data repository is configured
2018-11-26T13:08:49.807Z: logger D >  [1]zrobot 2|[Mon26 13:08] - .startup.py       :154 :j.zrobot_statup      - INFO     - starting node robot: zrobot server start --mode node --admin-organization bancadati.threefold.grid.farm01 --god --data-repo zdb://man-dc01.gig.tech:10005/ac1f6b479e68 --template-repo https://github.com/threefoldtech/0-templates#development
2018-11-26T13:08:51.183Z: pm D >  recurring '(kvm.monitor# kvm.monitor)' in 30s
2018-11-26T13:08:51.581Z: logger D >  [1]zrobot 2|[Mon26 13:08] - DbConfigManager.py:104 :anager.dbconfigmanager - INFO     - using namespace ac1f6b479e68
2018-11-26T13:08:51.644Z: logger D >  [1]zrobot 2|[Mon26 13:08] - DbConfigManager.py:104 :anager.dbconfigmanager - INFO     - using namespace ac1f6b479e68
2018-11-26T13:08:52.003Z: logger D >  [1]zrobot 2|[Mon26 13:08] - robot.py          :109 :j.zerorobot          - INFO     - data directory: /opt/var/data/zrobot
2018-11-26T13:08:52.003Z: logger D >  [1]zrobot 2|[Mon26 13:08] - robot.py          :110 :j.zerorobot          - INFO     - config directory: /root/configmgrsandboxes/ac1f6b479e68
2018-11-26T13:08:52.003Z: logger D >  [1]zrobot 2|[Mon26 13:08] - robot.py          :114 :j.zerorobot          - INFO     - sshkey used: /root/configmgrsandboxes/ac1f6b479e68/keys/key
2018-11-26T13:08:54.01Z: logger D >  [1]zrobot 2|[Mon26 13:08] - robot.py          :284 :j.zerorobot          - INFO     - admin JWT authentication enabled for organization: bancadati.threefold.grid.farm01
2018-11-26T13:08:54.673Z: pm D >  recurring '(monitor.cpu# monitor)' in 30s
2018-11-26T13:08:55.187Z: logger D >  [1]zrobot 2|Traceback (most recent call last):
  File "usr/local/bin/zrobot", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/code/github/threefoldtech/0-robot/cmd/zrobot", line 26, in <module>
    entry_point()
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/cli/server.py", line 127, in start
    god=god)
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/robot/robot.py", line 136, in start
    loader.load_services(config)
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/robot/loader.py", line 37, in load_services
    scol.load(tmplClass, service_details)
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/service_collection.py", line 94, in load
    service = template(name=service_detail['service']['name'], guid=guid, data=service_detail['data'])
  File "/opt/code/github/threefoldtech/0-templates/templates/zerotier_client/zerotier_client.py", line 18, in __init__
    if self.name in j.clients.zerotier.list():
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/JSBaseClassConfigs.py", line 69, in list
    for item in j.tools.configmanager.list(location=self.__jslocation__):
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/DbConfigManager.py", line 346, in list
    instances.append(kinfo['instance'])
TypeError: 'NoneType' object is not subscriptable

**Comment by zaibon** [comment]
fixed by : https://github.com/threefoldtech/jumpscale_core/commit/803b902f33471eade1d59a43ea3d5f56053712e8
