### ISSUE TITLE
python3 setup.py test causes js_config to run... breaking everything (/root/,profile_js invalid)

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#32]
```
cat /root/.profile_js
# environment variables
sshkeyname="id_rsa"
export sshkeyname

TERMINFO="xterm-256colors"
export TERMINFO

LC_ALL="en_US.UTF-8"
export LC_ALL

LANG="en_US.UTF-8"
export LANG

4f3fa2a4b1="ca0f8f040c"
export 4f3fa2a4b1

PATH="/opt/bin:${PATH}"
export PATH

# includes
```

which produces the following error, preventing everything from working:
```
[Thu09 09:47] - PrefabCore.py     :1123:j.prefabcore         - INFO     - RUN:js_config init -s -k /root/.ssh/id_rsa -p /opt/code/local/stdorg/config
Traceback (most recent call last):
  File "setup.py", line 105, in <module>
    'cmds/js_doc',
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/lkcl/src/jumpscale_core/tests/basic.py", line 14, in <module>
    j.tools.prefab.local.core.run("js_config init -s -k /root/.ssh/id_rsa -p %s" % path)
  File "/usr/local/lib/python3.6/dist-packages/JumpscalePrefab/PrefabCore.py", line 1133, in run
    cmd, checkok=checkok, die=die, showout=showout, env=env, timeout=timeout, sudo=sudo)
  File "/home/lkcl/src/jumpscale_core/Jumpscale/tools/executor/ExecutorLocal.py", line 131, in execute
    cmds2, die=die, showout=showout, timeout=timeout)
  File "/home/lkcl/src/jumpscale_core/Jumpscale/sal/process/SystemProcess.py", line 211, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute:    set -e
    [ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile'
    source /root/.bash_profile
    js_config init -s -k /root/.ssh/id_rsa -p /opt/code/local/stdorg/config

stderr:
    /root/.profile_js: line 14: 4f3fa2a4b1=ca0f8f040c: command not found
[Thu09 09:47] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - 
Could not execute:    set -e
    [ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile'
    source /root/.bash_profile
    js_config init -s -k /root/.ssh/id_rsa -p /opt/code/local/stdorg/config

stderr:
    /root/.profile_js: line 14: 4f3fa2a4b1=ca0f8f040c: command not found
```

**Comment by delandtj** [comment]
clearing out the contents of /root/.profile_js allows jumpscale (and testing) to proceed again
