### ISSUE TITLE
Jumpscale/data/cache/Cache.py __str__ method fails

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#35]
long story, accidentally walking all objects and printing them as strings, one of them happens to have an __str__ method.  however, j.data does not have a j.data.serializer instance... so this fails.

```
Traceback (most recent call last):
  File "jstestme.py", line 118, in <module>
    print (val, ty.currentLevel())
  File "/home/lkcl/src/jumpscale_core/Jumpscale/data/cache/Cache.py", line 182, in __str__
    out = j.data.serializer.yaml.dumps(res)
AttributeError: 'Data' object has no attribute 'serializer'
[Thu09 12:06] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - 'Data' object has no attribute 'serializer'
```

**Comment by delandtj** [comment]
commit db51310 - works now.  closing.
