### ISSUE TITLE
GitClient failing

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#60]
```
 jsconfig dir in: /opt/code/local/stdorg/config
Traceback (most recent call last):
  File "jstest.py", line 47, in <module>
    compare('j', jgen, dj, 2)
  File "jstest.py", line 45, in compare
    compare("%s.%s" % (tree, subname), subobj1, subobj2, depth-1)
  File "jstest.py", line 43, in compare
    subobj1 = getattr(obj1, subname)
  File "/usr/local/lib/python3.6/dist-packages/jumpscale.py", line 18, in _lazyprop
    setattr(self, attr_name, fn(self))
  File "/usr/local/lib/python3.6/dist-packages/jumpscale.py", line 1452, in currencylayer
    return JumpscaleLibClientsCurrencylayerCurrencyLayer()
  File "/usr/local/lib/python3.6/dist-packages/jumpscale.py", line 1253, in JumpscaleLibClientsCurrencylayerCurrencyLayer
    return _CurrencyLayer()
  File "/usr/local/lib/python3.6/dist-packages/JumpscaleLib/clients/currencylayer/CurrencyLayer.py", line 22, in __init__
    parent=None, template=TEMPLATE)
  File "/home/lkcl/src/jumpscale_core/Jumpscale/tools/configmanager/JSBaseClassConfig.py", line 36, in __init__
    self, instance=self._instance, data=data, template=self._template, ui=self._ui)
  File "/home/lkcl/src/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py", line 271, in _get_for_obj
    data=data)
  File "/home/lkcl/src/jumpscale_core/Jumpscale/tools/configmanager/Config.py", line 28, in __init__
    if not j.sal.fs.exists(self.path):
  File "/home/lkcl/src/jumpscale_core/Jumpscale/tools/configmanager/Config.py", line 69, in path
    j.data.text.toStr(j.tools.configmanager.path),
  File "/home/lkcl/src/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py", line 69, in path
    self.init()
  File "/home/lkcl/src/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py", line 517, in init
    cpath, giturl = self._findConfigRepo(die=False)
  File "/home/lkcl/src/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py", line 206, in _findConfigRepo
    self.logger.info("remote url: %s" % g.remoteUrl)
  File "/home/lkcl/src/jumpscale_core/Jumpscale/clients/git/GitClient.py", line 84, in remoteUrl
    raise j.exceptions.Input("There is not remote configured for this repository")
Jumpscale.errorhandling.JSExceptions.Input: ERROR: There is not remote configured for this repository ((type:input.error)
[Fri10 11:59] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - There is not remote configured for this repository
```

**Comment by delandtj** [comment]
there is no remote because there's no... remote.
as in, the repository /opt/code/local/stdorg/config is indeed local.... because it's been created... locally.
so ConfigFactory is *assuming* that there's a remote repo.... when there isn't one.
