### ISSUE TITLE
AttributeError: 'Dirs' object has no attribute 'JSCFGDIR'

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#61]
```
Traceback (most recent call last):
  File "jstest.py", line 47, in <module>
    compare('j', jgen, dj, 2)
  File "jstest.py", line 45, in compare
    compare("%s.%s" % (tree, subname), subobj1, subobj2, depth-1)
  File "jstest.py", line 43, in compare
    subobj1 = getattr(obj1, subname)
  File "/usr/local/lib/python3.6/dist-packages/jumpscale.py", line 18, in _lazyprop
    setattr(self, attr_name, fn(self))
  File "/usr/local/lib/python3.6/dist-packages/jumpscale.py", line 603, in objectinspector
    return JumpscaleLibToolsObjectinspectorObjectInspector()
  File "/usr/local/lib/python3.6/dist-packages/jumpscale.py", line 401, in JumpscaleLibToolsObjectinspectorObjectInspector
    return _ObjectInspector()
  File "/usr/local/lib/python3.6/dist-packages/JumpscaleLib/tools/objectinspector/ObjectInspector.py", line 198, in __init__
    self.apiFileLocation = j.sal.fs.joinPaths(j.dirs.JSCFGDIR, "codecompletionapi", "JumpscaleLib.api")
AttributeError: 'Dirs' object has no attribute 'JSCFGDIR'
[Fri10 12:42] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - 'Dirs' object has no attribute 'JSCFGDIR'

```

**Comment by delandtj** [comment]
sigh renaming to CFGDIR on the basis of a complete and utter guess at the contents of j.dirs.

**Comment by delandtj** [comment]
likewise in tools/testengine/TestEngine.py
