### ISSUE TITLE
CryptoError: Decryption failed. Ciphertext failed verification

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#62]
```
[Fri10 13:14] - Application.py    :105 :j.application        - INFO     - ***Application started***: jsshell
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: j.clients.zrobot.getall()
[Fri10 13:14] - SSHKeys.py        :153 :j.clients.sshkey     - INFO     - Will start agent
[Fri10 13:14] - SSHKeys.py        :274 :j.clients.sshkey     - INFO     - load ssh agent
[Fri10 13:14] - SSHKeys.py        :79  :j.clients.sshkey     - INFO     - load ssh key: /root/.ssh/id_rsa
---------------------------------------------------------------------------
CryptoError                               Traceback (most recent call last)
/usr/local/bin/js_shell in <module>()
----> 1 j.clients.zrobot.getall()

/usr/local/lib/python3.5/dist-packages/Jumpscale/tools/configmanager/JSBaseClassConfigs.py in getall(self)
     90         res = []
     91         for name in j.tools.configmanager.list(location=self.__jslocation__):
---> 92             res.append(self.get(name, create=False))
     93         return res

/usr/local/lib/python3.5/dist-packages/Jumpscale/tools/configmanager/JSBaseClassConfigs.py in get(self, instance, data, create, die, interactive, **kwargs)
     53             parent=self,
     54             interactive=interactive,
---> 55             **kwargs)
     56 
     57     def exists(self, instance):

/usr/local/lib/python3.5/dist-packages/JumpscaleZrobot/clients/zerorobot/ZeroRobotClient.py in __init__(self, instance, data, parent, template, ui, interactive)
     25         """
     26         data = data or {}
---> 27         super().__init__(instance=instance, data=data, parent=parent, template=_template, ui=ui, interactive=interactive)
     28         self._api = None
     29         self._jwt_expire_timestamp = None

/usr/local/lib/python3.5/dist-packages/Jumpscale/tools/configmanager/JSBaseClassConfig.py in __init__(self, instance, data, parent, template, ui, interactive)
     34 
     35         self._config = j.tools.configmanager._get_for_obj(
---> 36             self, instance=self._instance, data=data, template=self._template, ui=self._ui)
     37 
     38         if self.config.new and data == {} and self.interactive:

/usr/local/lib/python3.5/dist-packages/Jumpscale/tools/configmanager/Config.py in data(self)
    181                         if item != '' and item != '""':
    182                             res[key] = self.nacl.decryptSymmetric(
--> 183                                 item, hex=True).decode()
    184                         else:
    185                             res[key] = ''

/usr/local/lib/python3.5/dist-packages/Jumpscale/data/nacl/NACL.py in decryptSymmetric(self, data, secret, hex)
    195         if hex:
    196             data = self.hex_to_bin(data)
--> 197         res = box.decrypt(self.tobytes(data))
    198         box = None
    199         return res

/usr/local/lib/python3.5/dist-packages/nacl/secret.py in decrypt(self, ciphertext, nonce, encoder)
    123 
    124         plaintext = nacl.bindings.crypto_secretbox_open(ciphertext,
--> 125                                                         nonce, self._key)
    126 
    127         return plaintext

/usr/local/lib/python3.5/dist-packages/nacl/bindings/crypto_secretbox.py in crypto_secretbox_open(ciphertext, nonce, key)
     74         plaintext, padded, len(padded), nonce, key)
     75     ensure(res == 0, "Decryption failed. Ciphertext failed verification",
---> 76            raising=exc.CryptoError)
     77 
     78     plaintext = ffi.buffer(plaintext, len(padded))

/usr/local/lib/python3.5/dist-packages/nacl/exceptions.py in ensure(cond, *args, **kwds)
     66     if cond is True:
     67         return
---> 68     raise raising(*args)

CryptoError: Decryption failed. Ciphertext failed verification

```

**Comment by zaibon** [comment]
I also had the case multiple time, suddenly when trying to load from configs, I get this `Decryption failed` error. This is critical cause I then loose all my client/server configuration. Which in the case of the 0-robot client also mean we loose service secret, so we cannot access our own capacity anymore nor deleting the capacity either.

**Comment by zaibon** [comment]
The error happened again. This time on a system that is nearly idling. So I really don't know how this could happens. I don't think it's a corruption of the data itself anymore. There is really something wrong in the code of the config manager. 

This is not even the same error this time. Seems there is really something wrong in the way the code deals with the ssh-agent

```
[Tue13 21:05] - config_mgr.py     :31  :rorobot.dsl.config_mgr - ERROR    - error in config manager [Errno 32] Broken pipe
[Tue13 21:05] - base.py           :214 :s3_demo_1-2215eae7-d27d-4ed7-bfb3-38242b1fd9c9 (s3) - ERROR    - error executing action _monitor_minio:
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 619, in _monitor_minio
    self._get_namespace_by_address(connection_info)
  File "/opt/code/github/threefoldtech/0-templates/templates/s3/s3.py", line 98, in _get_namespace_by_address
    robot = self.api.robots.get(namespace['node'], namespace['url'])
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/dsl/config_mgr.py", line 97, in get
    return self._send_cmd(self._get, [instance, base_url])
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/dsl/config_mgr.py", line 40, in _send_cmd
    raise resp
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/dsl/config_mgr.py", line 26, in _worker
    result = func(*args)
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/dsl/config_mgr.py", line 48, in _get
    client = j.clients.zrobot.get(instance, interactive=False)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/JSBaseClassConfigs.py", line 43, in get
    return self._child_class(instance=instance, data=data, parent=self, interactive=interactive,**kwargs)
  File "/opt/code/github/threefoldtech/0-robot/JumpscaleZrobot/clients/zerorobot/ZeroRobotClient.py", line 27, in __init__
    super().__init__(instance=instance, data=data, parent=parent, template=_template, ui=ui, interactive=interactive)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/JSBaseClassConfig.py", line 28, in __init__
    self, instance=self._instance, data=data, template=self._template, ui=self._ui)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/FileConfigManager.py", line 132, in _get_for_obj
    sc = FileConfig(instance=instance, location=location, template=template, data=data)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/FileConfig.py", line 36, in __init__
    dataOnFS = self.data  # now decrypt
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/FileConfig.py", line 161, in data
    res[key] = self.nacl.decryptSymmetric(item, hex=True).decode()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/FileConfig.py", line 73, in nacl
    self._nacl = j.data.nacl.get(sshkeyname=j.tools.configmanager.keyname)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/data/nacl/NACLFactory.py", line 25, in get
    return NACL(name, secret, sshkeyname=j.tools.configmanager.keyname)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/data/nacl/NACL.py", line 59, in __init__
    self.sign_with_ssh_key(secretseed + secret))
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/data/nacl/NACL.py", line 252, in sign_with_ssh_key
    signeddata = j.data.nacl.agent.sign_ssh_data(hash)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/agent.py", line 416, in sign_ssh_data
    ptype, result = self.agent._send_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/agent.py", line 82, in _send_message
    self._conn.send(struct.pack(">I", len(msg)) + msg)
  File "/usr/local/lib/python3.5/dist-packages/gevent/_socket3.py", line 439, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe
```
