### ISSUE TITLE
j.tools.team.manager.test() fails

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#84]
** PLEASE IGNORE THIS BUGREPORT DO NOT ASSIGN IT TO ANY MILESTONE DO NOT ACTION IT, IT IS A PLACEHOLDER **

```
ERROR: test0070_j_tools_team_manager_test (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/git/GitFactory.py", line 288, in pullGitRepo
    interactive=interactive)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/git/GitFactory.py", line 444, in pullGitRepo
    self.execute(cmd, timeout=timeout, executor=executor)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/git/GitFactory.py", line 21, in execute
    return executor.execute(*args, **kwargs)
  File "/home/lkcl/src/jumpscale_core/Jumpscale/tools/executor/ExecutorLocal.py", line 137, in execute
    cmds2, die=die, showout=showout, timeout=timeout)
  File "/home/lkcl/src/jumpscale_core/Jumpscale/sal/process/SystemProcess.py", line 206, in execute
    raise RuntimeError(msg)
RuntimeError: 
Could not execute:    set -e
    mkdir -p /opt/code/docs/gig
    cd /opt/code/docs/gig
    git -c http.sslVerify=false clone   ssh://git@docs.grid.tf:10022/gig/data_team.git /opt/code/docs/gig/data_team

stderr:
    Cloning into '/opt/code/docs/gig/data_team'...
    ssh: connect to host docs.grid.tf port 10022: Connection refused
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

```

unit test can now be disabled and reference this bugreport until the unit test is fixed

**Comment by delandtj** [comment]
commit 4c1abd8
