### ISSUE TITLE
j.data.markdown.test2 fails

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#85]
** PLEASE IGNORE THIS BUGREPORT, DO NOT ASSIGN IT TO ANY MILESTONE **

```
FAIL: test0031_j_data_markdown_test2 (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lkcl/src/jumpscale_core/tests/jumpscale_test/test09_js_dynamic_walker.py", line 118, in _testfn
    newobj()
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/data/markdown/MarkdownFactory.py", line 53, in test2
    test()
  File "/home/lkcl/src/jumpscale_lib/JumpscaleLib/data/markdown/tests/test2.py", line 24, in test
    assert str(t).strip()==r.strip()
AssertionError
```

**Comment by delandtj** [comment]
commit 3bc4526
