### ISSUE TITLE
j.tools.configmanager.test fails

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#86]
** PLEASE IGNORE THIS BUGREPORT, DO NOT ACTION, DO NOT ASSIGN TO ANY MILESTONE **

```
FAIL: test0056_j_tools_configmanager_test (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lkcl/src/jumpscale_core/tests/jumpscale_test/test09_js_dynamic_walker.py", line 118, in _testfn
    newobj()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py", line 635, in test
    data = testinit()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/ConfigManager.py", line 631, in testinit
    assert self.j.tools.myconfig.config.data == data
AssertionError
```

**Comment by delandtj** [comment]
commit  0f201f5
