### ISSUE TITLE
j.tools.markdowndocs.test fails

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#87]
** PLEASE IGNORE THIS BUGREPORT, DO NOT ACTION, DO NOT ASSIGN TO ANY MILESTONE **

```
FAIL: test0065_j_tools_markdowndocs_test (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lkcl/src/jumpscale_core/tests/jumpscale_test/test09_js_dynamic_walker.py", line 118, in _testfn
    newobj()
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/tools/markdowndocs/MarkDownDocs.py", line 206, in test
    assert doc.data == {'color': 'green', 'importance': 'high', 'somelist': ['a', 'b', 'c']}
AssertionError

```

**Comment by delandtj** [comment]
commit f78e06a
