### ISSUE TITLE
j.tools.nodemgr.test fails

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#88]
** PLEASE IGNORE THIS BUGREPORT, DO NOT ACTION, DO NOT ASSIGN TO ANY MILESTONE**

```
FAIL: test0066_j_tools_nodemgr_test (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lkcl/src/jumpscale_core/tests/jumpscale_test/test09_js_dynamic_walker.py", line 118, in _testfn
    newobj()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/nodemgr/Nodes.py", line 90, in test
    self.set("myhost%s" % i, "127.0.0.%s" % i, 22, cat="testcat")
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/nodemgr/Nodes.py", line 36, in set
    assert j.data.types.string.check(zosclient)
AssertionError
```

**Comment by delandtj** [comment]
commit  f729ada
