### ISSUE TITLE
j.tools.numtools.test fails

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#89]
** PLEASE IGNORE THIS BUGREPORT, DO NOT ACTION, DO NOT ASSIGN TO ANY MILESTONE **

```
FAIL: test0067_j_tools_numtools_test (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lkcl/src/jumpscale_core/tests/jumpscale_test/test09_js_dynamic_walker.py", line 118, in _testfn
    newobj()
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/data/numtools/NumTools.py", line 278, in test
    ) * 10000000 == self.text2val("10 m egp")
AssertionError

```

**Comment by delandtj** [comment]
commit  2751b8b
