### ISSUE TITLE
j.tools.prefab.test fails

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscale_core#93]
** PLEASE IGNORE, DO NOT ACTION OR ASSIGN THIS BUGREPORT TO ANY MILESTONE **

```
ERROR: test0064_j_tools_prefab_test (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lkcl/src/jumpscale_core/tests/jumpscale_test/test09_js_dynamic_walker.py", line 118, in _testfn
    newobj()
  File "/opt/code/github/threefoldtech/jumpscale_prefab/JumpscalePrefab/PrefabFactory.py", line 115, in test
    c = e.prefab.apps.alba
AttributeError: 'PrefabCat' object has no attribute 'alba'
```

**Comment by delandtj** [comment]
commit 5b9991c
